### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by maliksyria** [electech6/NeRF-Based-SLAM-Incredible-Insights#1]
This repo seems very interesting. It would be an amazing idea to double the content in both English and Chinese languages ?

**Comment by shuttworth** [comment]
> This repo seems very interesting. It would be an amazing idea to double the content in both English and Chinese languages ?

Hello, thanks for your appreciate. Do you want the English notes or Chinese content?

**Comment by maliksyria** [comment]
Hello. Thanks for answer. 
English version if it's possible. This would be a good add to this repo to boost the number of audience to this content

**Comment by shuttworth** [comment]
> Hello. Thanks for answer. English version if it's possible. This would be a good add to this repo to boost the number of audience to this content

We have plans to update the English annotations, so stay tuned~

**Comment by maliksyria** [comment]
Great! Could you please tag me when you start to publish English content?
Thanks in advance!

**Comment by shuttworth** [comment]
> Great! Could you please tag me when you start to publish English content? Thanks in advance!

Okay
